title: TTNRT Blog
email: support@ttnrtsite.me
description: The offical TTNRT blog site
url: 'https://blog.ttnrtsite.me'
github_username: TTNRT
plugins:
  - jekyll-feed
git_repo: blog

# Build settings
markdown: kramdown